"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, Check, ChevronRight, ClipboardCheck, Code2, Flame, Gauge, GraduationCap, Lightbulb, LockKeyhole, LogOut, Menu, Play, ShieldCheck, Sparkles, Swords, Target, Trophy, UserPlus, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { curricula, type LearningMission, type LearningTrack } from "./curriculum";

declare global { interface Document { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } } }
type FriendProgress = { email:string; display_name?:string|null; track?:string|null; xp?:number|null; checkpoint?:number|null };
type JourneyState = Record<string, number[]>;

const tracks: { name:LearningTrack; icon:string; description:string }[] = [
  { name:"Java", icon:"J", description:"Core language to enterprise design" },
  { name:"Spring Boot", icon:"Sp", description:"Spring Core, APIs, data, security and production" },
];

function SideNav({ open, close, onNavigate }: { open:boolean; close:()=>void; onNavigate?:()=>void }) {
  return <aside className={`sidebar ${open?"sidebar-open":""}`}><div className="brand"><div className="brand-mark"><Swords/></div><div><strong>LEVELCRAFT</strong><span>ACADEMY</span></div></div><button className="close-nav" onClick={close} aria-label="Close navigation"><X/></button>
    <nav aria-label="Primary"><a className="active" href="#dashboard" onClick={onNavigate}><Gauge/> Command Center</a><a href="#curriculum" onClick={onNavigate}><BookOpen/> Curriculum</a><a href="#missions" onClick={onNavigate}><Target/> Missions</a><a href="#guild" onClick={onNavigate}><Users/> Guild Map</a><a href="#capstone" onClick={onNavigate}><Trophy/> Capstone</a></nav>
    <div className="sidebar-bottom"><div className="streak-card"><Flame/><div><b>Learn before you fight</b><span>Lessons unlock every quest</span></div></div><p>TRAINING PROTOCOL</p><small>Learn → practise → prove → progress.</small></div>
  </aside>;
}

function MissionPage({ mission, completed, onBack, onComplete }:{ mission:LearningMission; completed:boolean; onBack:()=>void; onComplete:(id:number)=>void }) {
  const [tab,setTab]=useState("learn"); const [answer,setAnswer]=useState(""); const [checked,setChecked]=useState<number[]>([]); const [evidence,setEvidence]=useState(""); const [quizChecked,setQuizChecked]=useState(false); const [claimed,setClaimed]=useState(false);
  useEffect(()=>{ setTab("learn");setAnswer("");setChecked([]);setEvidence("");setQuizChecked(false);setClaimed(false);window.scrollTo({top:0,behavior:"smooth"}); },[mission.id]);
  const quizCorrect=Number(answer)===mission.quiz.answer; const allChecked=checked.length===mission.quest.requirements.length; const evidenceReady=evidence.trim().length>=80; const canClaim=quizChecked&&quizCorrect&&allChecked&&evidenceReady;
  const toggle=(i:number)=>setChecked(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i]);
  const claim=()=>{ if(!canClaim)return; onComplete(mission.id);setClaimed(true); };
  if(claimed) return <main className="lesson-page"><div className="lesson-page-top"><button onClick={onBack}><ArrowLeft/> Quest map</button></div><div className="mission-complete"><div className="complete-emblem"><Trophy/></div><span>MISSION CLEARED</span><h2>{mission.title}</h2><p>Your lesson, practical evidence and knowledge check are recorded. The next mission is now unlocked.</p><Button onClick={onBack}>Continue your journey <ChevronRight/></Button></div></main>;
  return <main className="lesson-page"><header className="lesson-page-head"><div className="lesson-page-top"><button onClick={onBack}><ArrowLeft/> Quest map</button><span>{completed?<><Check/> Mission cleared</>:<>Mission {String(mission.id+1).padStart(2,"0")}</>}</span></div><div className="lesson-page-title"><div><span>{mission.phase} · Rank {mission.rank}</span><h1>{mission.title}</h1><p>{mission.objective}</p></div><div className="mission-reward"><b>+{mission.xp} XP</b><small>{mission.duration}</small></div></div></header>
    <Tabs value={tab} onValueChange={setTab} className="lesson-page-tabs"><div className="lesson-stage-bar"><TabsList><TabsTrigger value="learn"><BookOpen/> 1. Learn</TabsTrigger><TabsTrigger value="example"><Code2/> 2. Example</TabsTrigger><TabsTrigger value="quest"><Swords/> 3. Quest</TabsTrigger><TabsTrigger value="checkpoint"><ClipboardCheck/> 4. Checkpoint</TabsTrigger></TabsList></div>
      <TabsContent value="learn" className="lesson-scroll"><div className="lesson-callout"><Lightbulb/><div><b>Why this matters</b><p>{mission.lesson.why}</p></div></div><section className="lesson-section"><h3>Concept explained</h3><p>{mission.lesson.explanation}</p></section><div className="lesson-columns"><section><h3>Core ideas</h3><ul>{mission.lesson.keyPoints.map(x=><li key={x}><Check/>{x}</li>)}</ul></section><section><h3>Where you will use it</h3><ul>{mission.lesson.whenToUse.map(x=><li key={x}><ChevronRight/>{x}</li>)}</ul></section></div><section className="lesson-section caution"><h3>Points to remember</h3>{mission.lesson.notes.map(x=><p key={x}>• {x}</p>)}</section><div className="lesson-next"><span>Read the explanation before moving to the implementation.</span><Button onClick={()=>setTab("example")}>View implementation <ChevronRight/></Button></div></TabsContent>
      <TabsContent value="example" className="lesson-scroll"><section className="lesson-section"><h3>Reference implementation</h3><p>Read it line by line. Identify the responsibility of each statement and compare it with the notes from the lesson.</p><pre><code>{mission.lesson.code}</code></pre></section><div className="implementation-review"><h3>Implementation review</h3><div><span>1</span><p><b>Inputs and boundaries</b> — identify what enters the code and where invalid values are rejected.</p></div><div><span>2</span><p><b>Business behavior</b> — locate the rule being protected rather than just the syntax used.</p></div><div><span>3</span><p><b>Change pressure</b> — ask what would need to change when a new rule or implementation arrives.</p></div></div><div className="lesson-next"><span>Do not copy blindly; explain the design before using it.</span><Button onClick={()=>setTab("quest")}>Enter the quest <Swords/></Button></div></TabsContent>
      <TabsContent value="quest" className="lesson-scroll"><div className="quest-brief"><span>PRACTICAL QUEST</span><h3>{mission.quest.brief}</h3></div><section className="quest-requirements"><h3>Acceptance criteria</h3>{mission.quest.requirements.map((x,i)=><label key={x}><Checkbox checked={checked.includes(i)} onCheckedChange={()=>toggle(i)}/><span><b>{String(i+1).padStart(2,"0")}</b>{x}</span></label>)}</section><section className="lesson-section"><h3>Starting point</h3><pre><code>{mission.quest.starter}</code></pre></section><details className="hint-box"><summary><Lightbulb/> Need a hint?</summary><p>{mission.quest.hint}</p></details><section className="lesson-section expected"><h3>Expected behavior</h3><p>{mission.quest.expected}</p></section><section className="evidence-box"><h3>Your implementation evidence</h3><p>Paste the important part of your solution, repository/commit link, test output, or explain how you implemented and verified it. Minimum 80 characters.</p><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Describe your solution and verification…"/><small>{evidence.trim().length}/80 minimum</small></section><div className="lesson-next"><span>{allChecked&&evidenceReady?"Practical evidence ready.":"Complete every criterion and add implementation evidence."}</span><Button disabled={!allChecked||!evidenceReady} onClick={()=>setTab("checkpoint")}>Knowledge checkpoint <ChevronRight/></Button></div></TabsContent>
      <TabsContent value="checkpoint" className="lesson-scroll"><div className="quiz-card"><span>KNOWLEDGE CHECK</span><h3>{mission.quiz.question}</h3><RadioGroup value={answer} onValueChange={v=>{setAnswer(v);setQuizChecked(false)}}>{mission.quiz.options.map((option,i)=><label className={`quiz-option ${quizChecked&&i===mission.quiz.answer?"correct":""} ${quizChecked&&answer===String(i)&&i!==mission.quiz.answer?"wrong":""}`} key={option}><RadioGroupItem value={String(i)}/><span>{option}</span></label>)}</RadioGroup><Button variant="outline" disabled={answer===""} onClick={()=>setQuizChecked(true)}>Check answer</Button>{quizChecked&&<div className={`quiz-feedback ${quizCorrect?"success":"error"}`}><b>{quizCorrect?"Correct — checkpoint passed":"Not quite — review the lesson and try again"}</b><p>{mission.quiz.explanation}</p></div>}</div><div className="claim-panel"><div><span>MISSION VALIDATION</span><p><i className={allChecked?"done":""}>{allChecked?<Check/>:null}</i>Acceptance criteria confirmed</p><p><i className={evidenceReady?"done":""}>{evidenceReady?<Check/>:null}</i>Implementation evidence submitted</p><p><i className={quizCorrect&&quizChecked?"done":""}>{quizCorrect&&quizChecked?<Check/>:null}</i>Knowledge checkpoint passed</p></div><Button disabled={!canClaim} onClick={claim}><Trophy/> Complete mission & claim {mission.xp} XP</Button></div></TabsContent>
    </Tabs></main>;
}

export default function LevelCraftClient({user}:{user:{displayName:string;email:string}}){
  const [track,setTrack]=useState<LearningTrack>("Java"); const [journeys,setJourneys]=useState<JourneyState>({Java:[],"Spring Boot":[]}); const [completed,setCompleted]=useState<number[]>([]); const [friends,setFriends]=useState<FriendProgress[]>([]); const [friendEmail,setFriendEmail]=useState(""); const [loaded,setLoaded]=useState(false); const [sync,setSync]=useState("Loading checkpoint…"); const [navOpen,setNavOpen]=useState(false); const [picker,setPicker]=useState(false); const [activeMission,setActiveMission]=useState<LearningMission|null>(null);
  const missions=curricula[track]; const nextId=missions.find(m=>!completed.includes(m.id))?.id??missions.length; const xp=completed.reduce((n,id)=>n+(missions.find(m=>m.id===id)?.xp||0),0); const totalXp=missions.reduce((n,m)=>n+m.xp,0); const progress=Math.round(completed.length/missions.length*100); const current=missions[Math.min(nextId,missions.length-1)];
  const phases=useMemo(()=>Array.from(new Map(missions.map(m=>[m.phase,{name:m.phase,rank:m.rank,first:m.id,count:missions.filter(x=>x.phase===m.phase).length}])).values()),[missions]);
  const load=async()=>{try{const r=await fetch("/api/progress",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error();const saved:JourneyState=d.journeys||{Java:[],"Spring Boot":[]};const active=(d.own?.track==="Spring Boot"?"Spring Boot":"Java") as LearningTrack;setJourneys(saved);setTrack(active);setCompleted(saved[active]||d.own?.completed||[]);setFriends(d.friends||[]);setSync("Checkpoint synced")}catch{setSync("Sync unavailable")}finally{setLoaded(true)}};
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(!loaded)return;setJourneys(j=>({...j,[track]:completed}));const timer=window.setTimeout(async()=>{setSync("Saving checkpoint…");try{const r=await fetch("/api/progress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save_progress",track,level:"Beginner",completed})});if(!r.ok)throw new Error();setSync("Checkpoint synced")}catch{setSync("Save failed — retrying later")}},550);return()=>window.clearTimeout(timer)},[track,completed,loaded]);
  const chooseTrack=(next:LearningTrack)=>{setJourneys(j=>({...j,[track]:completed}));setTrack(next);setCompleted(journeys[next]||[]);setPicker(false)};
  const openMission=(mission:LearningMission)=>{if(mission.id>nextId&&!completed.includes(mission.id))return;setActiveMission(mission);window.history.pushState({mission:mission.id},"",`#mission-${mission.id+1}`)};
  const closeMission=()=>{setActiveMission(null);window.history.replaceState({},"",window.location.pathname+window.location.search+"#missions");window.setTimeout(()=>document.getElementById("missions")?.scrollIntoView({behavior:"smooth"}),0)};
  const completeMission=(id:number)=>setCompleted(c=>c.includes(id)?c:[...c,id].sort((a,b)=>a-b));
  const addFriend=async(e:React.FormEvent)=>{e.preventDefault();const email=friendEmail.trim();if(!email)return;setSync("Adding guild member…");const r=await fetch("/api/progress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add_friend",email})});const d=await r.json();if(r.ok){setFriendEmail("");await load()}else setSync(d.error||"Could not add friend")};
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"open_current_lesson",title:"Open current lesson",description:"Open the learner's next available Java or Spring Boot lesson.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){openMission(current);return{track,mission:current.title}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[current,track]);
  useEffect(()=>{if(!loaded)return;const match=window.location.hash.match(/^#mission-(\d+)$/);const id=match?Number(match[1])-1:-1;const mission=missions.find(m=>m.id===id);if(mission&&(mission.id<=nextId||completed.includes(mission.id)))setActiveMission(mission)},[loaded,track]);
  useEffect(()=>{const onPop=()=>{const match=window.location.hash.match(/^#mission-(\d+)$/);const id=match?Number(match[1])-1:-1;const mission=missions.find(m=>m.id===id);setActiveMission(mission&&(mission.id<=nextId||completed.includes(mission.id))?mission:null)};window.addEventListener("popstate",onPop);return()=>window.removeEventListener("popstate",onPop)},[missions,nextId,completed]);
  if(activeMission)return <div className="app-shell lesson-shell"><SideNav open={navOpen} close={()=>setNavOpen(false)} onNavigate={()=>setActiveMission(null)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)} aria-label="Close menu"/>}<MissionPage mission={activeMission} completed={completed.includes(activeMission.id)} onBack={closeMission} onComplete={completeMission}/></div>;
  return <div className="app-shell"><SideNav open={navOpen} close={()=>setNavOpen(false)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)} aria-label="Close menu"/>}<main id="dashboard" className="main-content"><header className="topbar"><button className="menu-btn" onClick={()=>setNavOpen(true)} aria-label="Open navigation"><Menu/></button><div><p>HUNTER / {user.email}</p><h1>Learning Command Center</h1></div><div className="top-actions"><span className="sync-status">{sync}</span><button className="track-switch" onClick={()=>setPicker(!picker)}><span>{track==="Java"?"J":"Sp"}</span><div><small>ACTIVE JOURNEY</small><b>{track}</b></div><ChevronRight/></button><a className="avatar" href="/signout-with-chatgpt?return_to=/" title="Sign out">{user.displayName.split(/\s|@/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}<i/></a></div></header>
    {picker&&<section className="track-picker"><div className="picker-head"><div><small>SELECT YOUR JOURNEY</small><h2>Java ecosystem learning paths</h2></div><button onClick={()=>setPicker(false)}><X/></button></div><div className="track-grid two">{tracks.map(t=><button className={track===t.name?"chosen":""} onClick={()=>chooseTrack(t.name)} key={t.name}><span>{t.icon}</span><div><b>{t.name}</b><small>{t.description}</small></div><em>{Math.round((journeys[t.name]?.length||0)/curricula[t.name].length*100)}%</em></button>)}</div></section>}
    <section className="rank-hero learning-hero"><div className="rank-emblem"><span>RANK</span><b>{current?.rank||"S"}</b><i/></div><div className="rank-copy"><p className="eyebrow"><GraduationCap/> STRUCTURED LEARNING JOURNEY</p><h2>{track}: {progress===100?"Expert Ascension complete":current.title}</h2><p>{progress===100?"All lessons, practical quests and checkpoints are complete.":current.objective}</p><div className="xp-row"><span>{xp.toLocaleString()} XP</span><Progress value={progress}/><span>{totalXp.toLocaleString()} XP</span></div></div><div className="rank-stats"><div><b>{completed.length}/{missions.length}</b><span>MISSIONS</span></div><div><b>{progress}%</b><span>JOURNEY</span></div><div><b>{phases.length}</b><span>GATES</span></div></div></section>
    <div className="learning-layout"><section className="primary-column"><div className="section-title" id="missions"><div><span>{progress===100?"JOURNEY COMPLETE":"NEXT LESSON + QUEST"}</span><h2>{progress===100?"Revisit any completed mission":current.title}</h2></div><small>Lessons cannot be skipped</small></div>{progress<100&&<article className="mission-card featured learning-card"><div className="mission-number">{String(current.id+1).padStart(2,"0")}</div><div className="mission-body"><div className="mission-tags"><span>{current.phase}</span><span>+{current.xp} XP</span><span>{current.duration}</span></div><h3>{current.title}</h3><p>{current.objective}</p><div className="mission-flow"><span><BookOpen/> Learn concepts</span><i/><span><Code2/> Study example</span><i/><span><Swords/> Build quest</span><i/><span><ClipboardCheck/> Pass checkpoint</span></div><Button className="start-btn" onClick={()=>openMission(current)}><Play/> Begin lesson</Button></div></article>}
      <section className="curriculum-section" id="curriculum"><div className="curriculum-head"><div><span>COMPLETE CURRICULUM</span><h2>{track} mission map</h2></div><p>{missions.length} guided lessons · practical builds · validated checkpoints</p></div><div className="mission-list">{missions.map(m=>{const done=completed.includes(m.id);const locked=m.id>nextId&&!done;return <button key={m.id} className={`curriculum-mission ${done?"done":""} ${locked?"locked":""} ${m.id===nextId?"current":""}`} onClick={()=>openMission(m)} disabled={locked}><span className="mission-state">{done?<Check/>:locked?<LockKeyhole/>:m.id+1}</span><div><small>{m.phase} · {m.duration}</small><h3>{m.title}</h3><p>{m.objective}</p></div><div className="mission-xp"><b>+{m.xp} XP</b><span>{done?"Revisit":locked?"Locked":"Start"}</span></div></button>})}</div></section>
      <section className="guild-section" id="guild"><div className="guild-head"><div><span>GUILD EXPEDITION</span><h2>{track} checkpoint map</h2><p>Compare saved progress with friends following this journey.</p></div><form onSubmit={addFriend}><input type="email" value={friendEmail} onChange={e=>setFriendEmail(e.target.value)} placeholder="friend@email.com" required/><Button type="submit"><UserPlus/> Add friend</Button></form></div><div className="arcade-map">{phases.map((phase,index)=>{const party=[{email:user.email,display_name:user.displayName,track,checkpoint:completed.length,xp},...friends].filter(f=>f.track===track&&Number(f.checkpoint||0)>=phase.first&&Number(f.checkpoint||0)<phase.first+phase.count);return <div className={`map-stage ${nextId>=phase.first?"reached":""}`} key={phase.name}><div className="map-line"/><div className="map-node"><span>{phase.rank}</span></div><b>{phase.name.replace(" Gate","")}</b><small>{phase.count} missions</small><div className="party-markers">{party.map((m,i)=><div className={`party-avatar ${m.email===user.email?"me":""}`} title={`${m.display_name||m.email} · ${m.xp||0} XP`} key={`${m.email}-${i}`}>{(m.display_name||m.email).split(/\s|@/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}</div>)}</div></div>})}</div></section>
    </section><aside className="right-column"><section className="panel course-rules"><div className="panel-title"><span>HOW PROGRESS WORKS</span><ShieldCheck/></div><ol><li><b>Learn</b><span>Read explanations, use cases and points to remember.</span></li><li><b>Study</b><span>Review a working implementation and its design.</span></li><li><b>Build</b><span>Complete every practical acceptance criterion.</span></li><li><b>Prove</b><span>Submit evidence and pass the knowledge check.</span></li></ol></section><section className="panel mastery"><div className="panel-title"><span>JOURNEY READINESS</span><b>{track}</b></div>{[["Lessons",progress],["Practical quests",progress],["Knowledge checks",progress],["Enterprise readiness",Math.max(0,progress-20)]].map(([l,v])=><div className="skill" key={l as string}><div><span>{l}</span><b>{v}%</b></div><Progress value={v as number}/></div>)}</section><section className="panel boss" id="capstone"><div className="boss-icon"><Trophy/></div><span>FINAL RANK TRIAL</span><h3>{missions.at(-1)?.title}</h3><p>{missions.at(-1)?.quest.brief}</p><div>{nextId>=missions.length-1?<Sparkles/>:<LockKeyhole/>}{nextId>=missions.length-1?"Available":"Complete prior missions"}</div></section><a className="signout-card" href="/signout-with-chatgpt?return_to=/"><LogOut/> Sign out of LevelCraft</a></aside></div><footer><span>LEVELCRAFT // LEARN → IMPLEMENT → VERIFY → ASCEND</span><span>Every checkpoint is saved to your account</span></footer></main></div>;
}
