"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BookOpen, Bug, Check, ChevronRight, ClipboardCheck, Code2, Crown, Flame, Gauge, Gift, GraduationCap, Lightbulb, LockKeyhole, LogOut, Menu, Play, ShieldCheck, Sparkles, Star, Swords, Target, Trophy, UserPlus, Users, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { learningCatalog, type LearningMission, type LearningTrack } from "./content/catalog";
import { learnerLevels, levelPrompt, type LearnerLevel } from "./content/learner-levels";
import { starterRewards } from "./content/rewards";
import { type SideQuest } from "./content/levelcraft-v2";
import type { MissionPageProps } from "@/modules/missions/model/mission-page";

const { tracks: curricula, training: trainingDepth, capstones: capstoneOptions, focusModules, sideQuests } = learningCatalog;

declare global { interface Document { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } } }
type FriendProgress = { email:string; display_name?:string|null; track?:string|null; xp?:number|null; checkpoint?:number|null };
type JourneyState = Record<string, number[]>;
type SideQuestState = Record<string, string[]>;
type CapstoneState = Record<string, string | null>;
type ProgressResponse = { own?: { track?: string; level?: string; completed?: number[] }; journeys?: JourneyState; sideQuests?: SideQuestState; capstones?: CapstoneState; friends?: FriendProgress[] };

const tracks: { name:LearningTrack; icon:string; description:string }[] = [
  { name:"Java", icon:"J", description:"Core language to enterprise design" },
  { name:"Spring Boot", icon:"Sp", description:"Spring Core, APIs, data, security and production" },
];

function SideNav({ open, close, onNavigate }: { open:boolean; close:()=>void; onNavigate?:()=>void }) {
  return <aside className={`sidebar ${open?"sidebar-open":""}`}><div className="brand"><div className="brand-mark"><Swords/></div><div><strong>LEVELCRAFT</strong><span>ACADEMY</span></div></div><button className="close-nav" onClick={close} aria-label="Close navigation"><X/></button>
    <nav aria-label="Primary"><a className="active" href="#dashboard" onClick={onNavigate}><Gauge/> Command Center</a><a href="#curriculum" onClick={onNavigate}><BookOpen/> Curriculum</a><a href="#missions" onClick={onNavigate}><Target/> Missions</a><a href="#side-quests" onClick={onNavigate}><Zap/> Side Quests</a><a href="#vault" onClick={onNavigate}><Gift/> Reward Vault</a><a href="#guild" onClick={onNavigate}><Users/> Guild Map</a><a href="#capstone" onClick={onNavigate}><Trophy/> Capstone</a></nav>
    <div className="sidebar-bottom"><div className="streak-card"><Flame/><div><b>Learn before you fight</b><span>Lessons unlock every quest</span></div></div><p>TRAINING PROTOCOL</p><small>Learn → practise → prove → progress.</small></div>
  </aside>;
}

export function LegacyMissionPage({ track, mission, completed, capstoneKey, learnerLevel="Beginner", onLevelChange=()=>undefined, onSelectCapstone, onBack, onComplete }: MissionPageProps) {
  const depth=trainingDepth[track][mission.id];
  const modules=focusModules[track]?.[mission.id]||[]; const capstones=capstoneOptions[track]; const isCapstone=mission.id===9;
  const [tab,setTab]=useState("briefing"); const [answer,setAnswer]=useState(""); const [checked,setChecked]=useState<number[]>([]); const [evidence,setEvidence]=useState(""); const [quizChecked,setQuizChecked]=useState(false); const [claimed,setClaimed]=useState(false); const [trainingComplete,setTrainingComplete]=useState(false);
  useEffect(()=>{ window.scrollTo({top:0,behavior:"smooth"}); },[]);
  const quizCorrect=Number(answer)===mission.quiz.answer; const allChecked=checked.length===mission.quest.requirements.length; const evidenceReady=evidence.trim().length>=80; const trained=trainingComplete||completed; const capstoneReady=!isCapstone||Boolean(capstoneKey); const canClaim=trained&&quizChecked&&quizCorrect&&allChecked&&evidenceReady&&capstoneReady;
  const toggle=(i:number)=>setChecked(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i]);
  const move=(next:string)=>{setTab(next);window.scrollTo({top:0,behavior:"smooth"})};
  const claim=()=>{ if(!canClaim)return; onComplete(mission.id);setClaimed(true); };
  if(claimed) return <main className="lesson-page"><div className="lesson-page-top"><button onClick={onBack}><ArrowLeft/> Quest map</button></div><div className="mission-complete"><div className="complete-emblem"><Trophy/></div><span>MISSION CLEARED</span><h2>{mission.title}</h2><p>You completed the guided training, practical evidence and rank trial. The next mission is now unlocked.</p><Button onClick={onBack}>Continue your journey <ChevronRight/></Button></div></main>;
  return <main className="lesson-page"><header className="lesson-page-head"><div className="lesson-page-top"><button onClick={onBack}><ArrowLeft/> Quest map</button><span>{completed?<><Check/> Mission cleared</>:<>Mission {String(mission.id+1).padStart(2,"0")}</>}</span></div><div className="lesson-page-title"><div><span>{mission.phase} · Rank {mission.rank}</span><h1>{mission.title}</h1><p>{mission.objective}</p></div><div className="mission-reward"><b>+{mission.xp} XP</b><small>{mission.duration}</small></div></div></header>
    <Tabs value={tab} onValueChange={move} className="lesson-page-tabs"><div className="lesson-stage-bar"><TabsList><TabsTrigger value="briefing"><BookOpen/> 1. Briefing</TabsTrigger><TabsTrigger value="training"><Code2/> 2. Training</TabsTrigger><TabsTrigger value="notes"><ShieldCheck/> 3. Hunter Notes</TabsTrigger><TabsTrigger value="quest"><Swords/> 4. Quest</TabsTrigger><TabsTrigger value="checkpoint"><ClipboardCheck/> 5. Rank Trial</TabsTrigger></TabsList></div>
      <TabsContent value="briefing" className="lesson-scroll"><div className="system-briefing"><span>SYSTEM BRIEFING</span><h2>Start here—no prior knowledge assumed</h2><p>{depth.opening}</p></div><section className="learner-level-panel"><div><span>YOUR EXPLANATION DEPTH</span><h3>{learnerLevel} path</h3><p>{levelPrompt(learnerLevel)}</p></div><div className="learner-level-options" role="group" aria-label="Learner experience level">{learnerLevels.map(level=><button key={level.id} className={learnerLevel===level.id?"selected":""} onClick={()=>onLevelChange(level.id)}><b>{level.id}</b><small>{level.description}</small></button>)}</div></section><section className="mission-roadmap"><span>WHAT THIS MISSION WILL DO</span><div><article><b>1 · Understand</b><p>Build vocabulary and a mental model before framework code.</p></article><article><b>2 · Follow</b><p>Use supplied starter code and make one guided change at a time.</p></article><article><b>3 · Compare</b><p>Study use cases, strengths, weaknesses and valid alternatives.</p></article><article><b>4 · Prove</b><p>Complete an independent task and explain your evidence.</p></article></div></section><section className="scenario-card"><div><span>REAL-WORLD MENTAL MODEL</span><h3>The situation</h3></div><p>{depth.scenario}</p></section><section className="depth-section"><div className="depth-heading"><span>FOUNDATIONAL LOADOUT</span><h2>What you need before this mission</h2><p>These are explanations, not an entrance exam. Read each one before continuing.</p></div><div className="prerequisite-grid">{depth.prerequisites.map(x=><article key={x.name}><b>{x.name}</b><p>{x.explanation}</p></article>)}</div></section><section className="depth-section"><div className="depth-heading"><span>TERMINOLOGY DECODER</span><h2>Translate the language</h2><p>Learn the words before being asked to use them.</p></div><div className="term-list">{depth.terms.map((x,i)=><article key={x.term}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{x.term}</h3><p>{x.meaning}</p><small>Example: {x.example}</small></div></article>)}</div></section><div className="coach-prompt"><Lightbulb/><div><span>CHECK YOUR FOUNDATION</span><p>{learnerLevel==="Beginner"?`In plain language, what problem is this mission trying to solve? Use one example from the situation above.`:depth.coachQuestion}</p><small>This question only uses concepts introduced above. If you cannot answer yet, revisit the terminology—that is training, not failure.</small></div></div><div className="lesson-next"><span>Next: follow the guided lab one deliberate step at a time.</span><Button onClick={()=>move("training")}>Begin guided training <ChevronRight/></Button></div></TabsContent>
      <TabsContent value="training" className="lesson-scroll"><div className="training-intro"><span>GUIDED TRAINING</span><h2>Observe → change → verify</h2><p>You are not solving the quest yet. Start from the supplied code, change one thing, and compare the result with the expected observation.</p></div><section className="workspace-guide"><div><span>WHERE TO DO THIS</span><h3>Use a local Java 17 practice workspace</h3><p>LevelCraft does not execute Java or Spring Boot inside the browser yet. Use IntelliJ IDEA, VS Code, Eclipse, or another Java 17 environment. A complete starting example is supplied so a beginner is never asked to invent missing classes before learning the concept.</p></div><ol><li>Create a fresh practice project or branch.</li><li>Copy the starter and make sure it runs first.</li><li>Apply one guided change at a time.</li><li>Compare your result with the expected observation.</li></ol></section><section className="starter-workspace"><span>STARTER WORKSPACE · BEFORE STEP 1</span><h3>Your known-good starting point</h3><p>Read and run this example before modifying it. The later quest remains independent.</p><pre><code>{mission.lesson.code}</code></pre></section><div className="training-steps">{depth.guided.map((x,i)=><article key={x.title}><div className="step-rank"><span>STEP</span><b>{i+1}</b></div><div><h3>{x.title}</h3><p><b>Starting from:</b> the known-good workspace above.</p><p><b>Do:</b> {x.action}</p><p><b>Why:</b> {x.why}</p><div className="observe"><span>EXPECTED OBSERVATION</span>{x.observe}</div></div></article>)}</div><section className="lesson-section code-lab"><span>REFERENCE REVIEW</span><h3>Trace the finished behavior</h3><p>Identify the inputs, decisions, dependencies and result. Add your own comments explaining why each important line exists.</p><pre><code>{mission.lesson.code}</code></pre></section><label className={`training-confirm ${trainingComplete?"complete":""}`}><Checkbox checked={trainingComplete} onCheckedChange={v=>setTrainingComplete(v===true)}/><span><b>I completed the guided steps</b><small>I ran the starting example, made the changes, checked the observations and can explain the concept.</small></span></label><div className="lesson-next"><span>{trainingComplete?"Training gate cleared.":"Complete the lab before the independent quest unlocks."}</span><Button disabled={!trainingComplete&&!completed} onClick={()=>move("notes")}>Open Hunter Notes <ChevronRight/></Button></div></TabsContent>
      <TabsContent value="notes" className="lesson-scroll"><div className="lesson-callout"><Lightbulb/><div><b>Why this matters</b><p>{mission.lesson.why}</p></div></div><section className="lesson-section"><span className="section-kicker">HUNTER NOTES · REVISION</span><h3>Concept recap</h3><p>{mission.lesson.explanation}</p></section><div className="lesson-columns"><section><h3>Advantages and core rules</h3><ul>{mission.lesson.keyPoints.map(x=><li key={x}><Check/>{x}</li>)}</ul></section><section><h3>Real use cases</h3><ul>{mission.lesson.whenToUse.map(x=><li key={x}><ChevronRight/>{x}</li>)}</ul></section></div><section className="decision-guide"><div className="depth-heading"><span>ENGINEERING DECISION GUIDE</span><h2>Benefits, costs and alternatives</h2><p>A concept is not mastered until you know when not to use it.</p></div><div><article><h3>What it gives you</h3><p>{mission.lesson.keyPoints.slice(0,2).join(" ")}</p></article><article><h3>What it can cost</h3><p>{mission.lesson.notes.slice(0,2).join(" ")}</p></article><article><h3>What to compare</h3><p>{depth.coaching.slice(0,2).map(item=>item.better).join(" ")}</p></article></div></section>{modules.length>0&&<section className="focus-campaign"><div className="depth-heading"><span>{track==="Java"&&mission.id===6?"MULTITHREADING WAR CAMP":"DEEP-DIVE MODULES"}</span><h2>{track==="Java"&&mission.id===6?"Five battles. One concurrency foundation.":"Broaden the concept before choosing a path"}</h2><p>Each module includes the alternatives and trade-offs required for informed engineering decisions.</p></div><div className="focus-module-grid">{modules.map((module,i)=><article key={module.title}><div className="focus-index">{String(i+1).padStart(2,"0")}</div><div><h3>{module.title}</h3><p>{module.purpose}</p><ul>{module.concepts.map(concept=><li key={concept}><Check/>{concept}</li>)}</ul><div className="module-challenge"><Swords/><span><b>Battle drill</b>{module.challenge}</span></div></div></article>)}</div></section>}<section className="depth-section"><div className="depth-heading"><span>SYSTEM COACHING</span><h2>Common mistake → stronger approach</h2></div><div className="coaching-grid">{depth.coaching.map(x=><article key={x.wrong}><div><span>WEAK MOVE</span><p>{x.wrong}</p></div><ChevronRight/><div><span>BETTER MOVE</span><p>{x.better}</p><small>{x.reason}</small></div></article>)}</div></section><section className="lesson-section caution"><h3>Trade-offs and limits to remember</h3>{mission.lesson.notes.map(x=><p key={x}>• {x}</p>)}</section><div className="lesson-next"><span>{trained?"Independent quest unlocked.":"Review mode lets you inspect the quest; completing training remains required for XP."}</span><Button onClick={()=>move("quest")}>Inspect independent quest <Swords/></Button></div></TabsContent>
      <TabsContent value="quest" className="lesson-scroll"><div className="quest-brief"><span>{isCapstone?"CAPSTONE DOMAIN SELECTION":"INDEPENDENT PRACTICAL QUEST"}</span><h3>{mission.quest.brief}</h3><p>{isCapstone?"Choose the domain that keeps you curious. The engineering standards remain equally demanding.":"No step-by-step solution is provided here. Use the training, notes and feedback above."}</p></div>{isCapstone&&<section className="capstone-selector"><div className="depth-heading"><span>CHOOSE YOUR WAR</span><h2>One standard. Five domains.</h2><p>Your choice is saved to this learning journey and can be changed until the capstone is completed.</p></div><div className="capstone-grid">{capstones.map(option=><button key={option.id} className={capstoneKey===option.id?"selected":""} onClick={()=>onSelectCapstone(option.id)}><span>{option.domain}</span><h3>{option.title}</h3><p>{option.brief}</p><ul>{option.coreFeatures.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><small><Crown/> Hard mode: {option.hardMode}</small></button>)}</div></section>}<section className="quest-requirements"><h3>Acceptance criteria</h3>{mission.quest.requirements.map((x,i)=><label key={x}><Checkbox checked={checked.includes(i)} onCheckedChange={()=>toggle(i)}/><span><b>{String(i+1).padStart(2,"0")}</b>{x}</span></label>)}</section><section className="lesson-section"><h3>Starting point</h3><pre><code>{mission.quest.starter}</code></pre></section><details className="hint-box"><summary><Lightbulb/> Need a hint?</summary><p>{mission.quest.hint}</p></details><section className="lesson-section expected"><h3>Expected behavior</h3><p>{mission.quest.expected}</p></section><section className="evidence-box"><h3>Your implementation evidence</h3><p>Paste the important part of your solution, repository/commit link, test output, or explain how you implemented and verified it. Minimum 80 characters.</p><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Describe your solution, decisions and verification…"/><small>{evidence.trim().length}/80 minimum</small></section><div className="lesson-next"><span>{allChecked&&evidenceReady&&capstoneReady?"Practical evidence ready.":isCapstone&&!capstoneKey?"Choose a capstone domain before the rank trial.":"Complete every criterion and add implementation evidence."}</span><Button disabled={!allChecked||!evidenceReady||!capstoneReady} onClick={()=>move("checkpoint")}>Enter rank trial <ChevronRight/></Button></div></TabsContent>
      <TabsContent value="checkpoint" className="lesson-scroll"><div className="coach-prompt trial-question"><Lightbulb/><div><span>EXPLAIN BEFORE YOU ANSWER</span><p>{depth.coachQuestion}</p><small>Your explanation is the evidence that the concept is yours—not merely memorized.</small></div></div><div className="quiz-card"><span>RANK TRIAL · KNOWLEDGE CHECK</span><h3>{mission.quiz.question}</h3><RadioGroup value={answer} onValueChange={v=>{setAnswer(v);setQuizChecked(false)}}>{mission.quiz.options.map((option,i)=><label className={`quiz-option ${quizChecked&&i===mission.quiz.answer?"correct":""} ${quizChecked&&answer===String(i)&&i!==mission.quiz.answer?"wrong":""}`} key={option}><RadioGroupItem value={String(i)}/><span>{option}</span></label>)}</RadioGroup><Button variant="outline" disabled={answer===""} onClick={()=>setQuizChecked(true)}>Check answer</Button>{quizChecked&&<div className={`quiz-feedback ${quizCorrect?"success":"error"}`}><b>{quizCorrect?"Correct — rank trial passed":"Not yet — return to training and try again"}</b><p>{mission.quiz.explanation}</p></div>}</div><div className="claim-panel"><div><span>MISSION VALIDATION</span><p><i className={trained?"done":""}>{trained?<Check/>:null}</i>Guided training completed</p><p><i className={allChecked?"done":""}>{allChecked?<Check/>:null}</i>Acceptance criteria confirmed</p><p><i className={evidenceReady?"done":""}>{evidenceReady?<Check/>:null}</i>Implementation evidence submitted</p><p><i className={quizCorrect&&quizChecked?"done":""}>{quizCorrect&&quizChecked?<Check/>:null}</i>Knowledge checkpoint passed</p></div><Button disabled={!canClaim} onClick={claim}><Trophy/> Complete mission & claim {mission.xp} XP</Button></div></TabsContent>
    </Tabs></main>;
}

function SideQuestPage({quest,completed,onBack,onComplete}:{quest:SideQuest;completed:boolean;onBack:()=>void;onComplete:(id:string)=>void}){
  const [checked,setChecked]=useState<number[]>([]); const [evidence,setEvidence]=useState(""); const [claimed,setClaimed]=useState(false);
  const ready=checked.length===quest.requirements.length&&evidence.trim().length>=80;
  const toggle=(i:number)=>setChecked(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i]);
  if(claimed)return <main className="lesson-page side-quest-page"><div className="reward-reveal"><div className="reward-burst"><Gift/></div><span>SIDE QUEST CLEARED</span><h1>{quest.reward.name}</h1><p>{quest.reward.detail}</p><div className="reward-chip">{quest.reward.kind} · +{quest.xp} XP</div><Button onClick={onBack}>Return to command center <ChevronRight/></Button></div></main>;
  return <main className="lesson-page side-quest-page"><header className="lesson-page-head"><div className="lesson-page-top"><button onClick={onBack}><ArrowLeft/> Command Center</button><span><Zap/> Optional training</span></div><div className="lesson-page-title"><div><span>{quest.type} side quest · {quest.threat} threat</span><h1>{quest.title}</h1><p>{quest.brief}</p></div><div className="mission-reward"><b>+{quest.xp} XP</b><small>{quest.reward.kind} reward</small></div></div></header><div className="lesson-scroll side-quest-content"><section className="system-choice"><div><span>THE SYSTEM OFFERS A CHOICE</span><h2>Strengthen the foundation—or continue the main campaign.</h2><p>Side quests are optional and never block progression. Complete them when you want more practice, stronger judgment or the reward.</p></div><Button variant="outline" onClick={onBack}>Continue main progression</Button></section><section className="side-quest-skills"><h3>Abilities under pressure</h3><div>{quest.skills.map(skill=><span key={skill}><Star/>{skill}</span>)}</div></section><section className="quest-requirements"><h3>Victory conditions</h3>{quest.requirements.map((requirement,i)=><label key={requirement}><Checkbox checked={checked.includes(i)} onCheckedChange={()=>toggle(i)}/><span><b>{String(i+1).padStart(2,"0")}</b>{requirement}</span></label>)}</section><details className="hint-box"><summary><Lightbulb/> Request a system hint</summary><p>{quest.hint}</p></details><section className="evidence-box"><h3>Battle report</h3><p>Explain the implementation, decision, test evidence or incident reasoning. Minimum 80 characters.</p><textarea value={evidence} onChange={event=>setEvidence(event.target.value)} placeholder="What did you change, why did you choose it, and how did you prove it?"/><small>{evidence.trim().length}/80 minimum</small></section><section className="side-reward-preview"><Gift/><div><span>QUEST REWARD</span><h3>{quest.reward.name}</h3><p>{quest.reward.detail}</p></div></section><div className="lesson-next"><span>{completed?"Quest already cleared. You may revisit the drill.":ready?"Victory conditions satisfied.":"Complete the conditions and battle report."}</span><Button disabled={!ready||completed} onClick={()=>{onComplete(quest.id);setClaimed(true)}}><Trophy/> {completed?"Reward claimed":"Clear quest & claim reward"}</Button></div></div></main>;
}

export default function LevelCraftClient({user}:{user:{displayName:string;email:string}}){
  const router=useRouter();
  const [learnerLevel,setLearnerLevel]=useState<LearnerLevel>("Beginner");
  const [track,setTrack]=useState<LearningTrack>("Java"); const [journeys,setJourneys]=useState<JourneyState>({Java:[],"Spring Boot":[]}); const [completed,setCompleted]=useState<number[]>([]); const [sideQuestJourneys,setSideQuestJourneys]=useState<SideQuestState>({Java:[],"Spring Boot":[]}); const [sideCompleted,setSideCompleted]=useState<string[]>([]); const [capstoneChoices,setCapstoneChoices]=useState<CapstoneState>({Java:null,"Spring Boot":null}); const [capstoneKey,setCapstoneKey]=useState<string|null>(null); const [friends,setFriends]=useState<FriendProgress[]>([]); const [friendEmail,setFriendEmail]=useState(""); const [loaded,setLoaded]=useState(false); const [sync,setSync]=useState("Loading checkpoint…"); const [navOpen,setNavOpen]=useState(false); const [picker,setPicker]=useState(false); const [activeSideQuest,setActiveSideQuest]=useState<SideQuest|null>(null);
  const missions=curricula[track]; const progressionNextId=missions.find(m=>!completed.includes(m.id))?.id??missions.length; const nextId=missions.length; const missionXp=completed.reduce((n,id)=>n+(missions.find(m=>m.id===id)?.xp||0),0); const sideXp=sideCompleted.reduce((sum,id)=>sum+(sideQuests[track].find(q=>q.id===id)?.xp||0),0); const xp=missionXp+sideXp; const totalXp=missions.reduce((n,m)=>n+m.xp,0)+sideQuests[track].reduce((n,q)=>n+q.xp,0); const progress=Math.round(completed.length/missions.length*100); const current=missions[Math.min(progressionNextId,missions.length-1)]; const availableSideQuests=sideQuests[track]; const unlockedRewards=[...starterRewards,...sideQuests[track].filter(quest=>sideCompleted.includes(quest.id)).map(quest=>({...quest.reward,symbol:quest.reward.kind==="Sticker"?"✦":quest.reward.kind==="Quote"?"❝":"♛"}))];
  const phases=useMemo(()=>Array.from(new Map(missions.map(m=>[m.phase,{name:m.phase,rank:m.rank,first:m.id,count:missions.filter(x=>x.phase===m.phase).length}])).values()),[missions]);
  const load=async()=>{try{const r=await fetch("/api/progress",{cache:"no-store"});const d=await r.json() as ProgressResponse;if(!r.ok)throw new Error();const saved:JourneyState=d.journeys||{Java:[],"Spring Boot":[]};const savedSide:SideQuestState=d.sideQuests||{Java:[],"Spring Boot":[]};const savedCapstones:CapstoneState=d.capstones||{Java:null,"Spring Boot":null};const active=(d.own?.track==="Spring Boot"?"Spring Boot":"Java") as LearningTrack;const savedLevel=d.own?.level==="Fresher"?"Beginner":d.own?.level;setJourneys(saved);setSideQuestJourneys(savedSide);setCapstoneChoices(savedCapstones);setTrack(active);setLearnerLevel((savedLevel||"Beginner") as LearnerLevel);setCompleted(saved[active]||d.own?.completed||[]);setSideCompleted(savedSide[active]||[]);setCapstoneKey(savedCapstones[active]||null);setFriends(d.friends||[]);setSync("Checkpoint synced")}catch{setSync("Sync unavailable")}finally{setLoaded(true)}};
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{if(!loaded)return;const timer=window.setTimeout(async()=>{setSync("Saving checkpoint…");try{const r=await fetch("/api/progress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save_progress",track,level:learnerLevel,completed,sideQuests:sideCompleted,capstoneKey})});if(!r.ok)throw new Error();setSync("Checkpoint synced")}catch{setSync("Save failed — retrying later")}},550);return()=>window.clearTimeout(timer)},[track,learnerLevel,completed,sideCompleted,capstoneKey,loaded]);
  const chooseTrack=(next:LearningTrack)=>{setJourneys(j=>({...j,[track]:completed}));setSideQuestJourneys(j=>({...j,[track]:sideCompleted}));setCapstoneChoices(j=>({...j,[track]:capstoneKey}));setTrack(next);setCompleted(journeys[next]||[]);setSideCompleted(sideQuestJourneys[next]||[]);setCapstoneKey(capstoneChoices[next]||null);setPicker(false)};
  const openMission=(mission:LearningMission)=>{const slug=track==="Java"?"java":"spring-boot";router.push(`/mission/${slug}/${mission.id+1}`)};
  const completeSideQuest=(id:string)=>setSideCompleted(c=>c.includes(id)?c:[...c,id]);
  const addFriend=async(e:React.FormEvent)=>{e.preventDefault();const email=friendEmail.trim();if(!email)return;setSync("Adding guild member…");const r=await fetch("/api/progress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add_friend",email})});const d=await r.json() as {error?:string};if(r.ok){setFriendEmail("");await load()}else setSync(d.error||"Could not add friend")};
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"open_current_lesson",title:"Open current lesson",description:"Open the learner's next available Java or Spring Boot lesson.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){const slug=track==="Java"?"java":"spring-boot";router.push(`/mission/${slug}/${current.id+1}`);return{track,mission:current.title}}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[current,track,router]);
  if(activeSideQuest)return <div className="app-shell lesson-shell"><SideNav open={navOpen} close={()=>setNavOpen(false)} onNavigate={()=>setActiveSideQuest(null)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)} aria-label="Close menu"/>}<SideQuestPage quest={activeSideQuest} completed={sideCompleted.includes(activeSideQuest.id)} onBack={()=>{setActiveSideQuest(null);window.location.hash="side-quests"}} onComplete={completeSideQuest}/></div>;
  return <div className="app-shell"><SideNav open={navOpen} close={()=>setNavOpen(false)}/>{navOpen&&<button className="scrim" onClick={()=>setNavOpen(false)} aria-label="Close menu"/>}<main id="dashboard" className="main-content"><header className="topbar"><button className="menu-btn" onClick={()=>setNavOpen(true)} aria-label="Open navigation"><Menu/></button><div><p>HUNTER / {user.email}</p><h1>Learning Command Center</h1></div><div className="top-actions"><span className="sync-status">{sync}</span><button className="track-switch" onClick={()=>setPicker(!picker)}><span>{track==="Java"?"J":"Sp"}</span><div><small>ACTIVE JOURNEY</small><b>{track}</b></div><ChevronRight/></button><a className="avatar" href="/signout-with-chatgpt?return_to=/" title="Sign out">{user.displayName.split(/\s|@/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}<i/></a></div></header>
    {picker&&<section className="track-picker"><div className="picker-head"><div><small>SELECT YOUR JOURNEY</small><h2>Java ecosystem learning paths</h2></div><button onClick={()=>setPicker(false)}><X/></button></div><div className="track-grid two">{tracks.map(t=><button className={track===t.name?"chosen":""} onClick={()=>chooseTrack(t.name)} key={t.name}><span>{t.icon}</span><div><b>{t.name}</b><small>{t.description}</small></div><em>{Math.round((journeys[t.name]?.length||0)/curricula[t.name].length*100)}%</em></button>)}</div></section>}
    <section className="rank-hero learning-hero"><div className="rank-emblem"><span>RANK</span><b>{current?.rank||"S"}</b><i/></div><div className="rank-copy"><p className="eyebrow"><GraduationCap/> STRUCTURED LEARNING JOURNEY</p><h2>{track}: {progress===100?"Expert Ascension complete":current.title}</h2><p>{progress===100?"All lessons, practical quests and checkpoints are complete.":current.objective}</p><div className="xp-row"><span>{xp.toLocaleString()} XP</span><Progress value={progress}/><span>{totalXp.toLocaleString()} XP</span></div></div><div className="rank-stats"><div><b>{completed.length}/{missions.length}</b><span>MISSIONS</span></div><div><b>{progress}%</b><span>JOURNEY</span></div><div><b>{phases.length}</b><span>GATES</span></div></div></section>
    <div className="learning-layout"><section className="primary-column"><div className="section-title" id="missions"><div><span>{progress===100?"JOURNEY COMPLETE":"NEXT RECOMMENDED MISSION"}</span><h2>{progress===100?"Revisit any mission":current.title}</h2></div><small>Content review mode · every mission is open</small></div>{progress<100&&<article className="mission-card featured learning-card"><div className="mission-number">{String(current.id+1).padStart(2,"0")}</div><div className="mission-body"><div className="mission-tags"><span>{current.phase}</span><span>+{current.xp} XP</span><span>{current.duration}</span></div><h3>{current.title}</h3><p>{current.objective}</p><div className="mission-flow"><span><BookOpen/> System briefing</span><i/><span><Code2/> Guided training</span><i/><span><ShieldCheck/> Hunter notes</span><i/><span><Swords/> Independent quest</span><i/><span><ClipboardCheck/> Rank trial</span></div><Button className="start-btn" onClick={()=>openMission(current)}><Play/> Begin training</Button></div></article>}
      <section className="curriculum-section" id="curriculum"><div className="curriculum-head"><div><span>COMPLETE CURRICULUM</span><h2>{track} mission map</h2></div><p>{missions.length} guided lessons · practical builds · validated checkpoints</p></div><div className="mission-list">{missions.map(m=>{const done=completed.includes(m.id);const locked=m.id>nextId&&!done;return <button key={m.id} className={`curriculum-mission ${done?"done":""} ${locked?"locked":""} ${m.id===nextId?"current":""}`} onClick={()=>openMission(m)} disabled={locked}><span className="mission-state">{done?<Check/>:locked?<LockKeyhole/>:m.id+1}</span><div><small>{m.phase} · {m.duration}</small><h3>{m.title}</h3><p>{m.objective}</p></div><div className="mission-xp"><b>+{m.xp} XP</b><span>{done?"Revisit":locked?"Locked":"Start"}</span></div></button>})}</div></section>
      <section className="side-quest-section" id="side-quests"><div className="curriculum-head"><div><span>SYSTEM CHOICE</span><h2>Optional side quests</h2></div><p>Practise judgment without interrupting the main campaign.</p></div>{availableSideQuests.length===0?<div className="side-quest-empty"><LockKeyhole/><div><h3>Complete the first major milestone</h3><p>The System will offer focused side quests after a gate is cleared.</p></div></div>:<div className="side-quest-grid">{availableSideQuests.map(quest=>{const done=sideCompleted.includes(quest.id);return <button key={quest.id} className={done?"cleared":""} onClick={()=>setActiveSideQuest(quest)}><div className="side-quest-top"><span>{quest.type}</span><em>{quest.threat}</em></div><div className="side-quest-icon">{quest.type==="Debugging"?<Bug/>:quest.type==="Incident"?<Flame/>:quest.type==="Decision"?<Lightbulb/>:<Zap/>}</div><h3>{quest.title}</h3><p>{quest.brief}</p><div className="side-quest-footer"><span>{done?<><Check/> Cleared</>:<>+{quest.xp} XP</>}</span><b>{quest.reward.kind}: {quest.reward.name}</b></div></button>})}</div>}</section>
      <section className="guild-section" id="guild"><div className="guild-head"><div><span>GUILD EXPEDITION</span><h2>{track} checkpoint map</h2><p>Compare saved progress with friends following this journey.</p></div><form onSubmit={addFriend}><input type="email" value={friendEmail} onChange={e=>setFriendEmail(e.target.value)} placeholder="friend@email.com" required/><Button type="submit"><UserPlus/> Add friend</Button></form></div><div className="arcade-map">{phases.map((phase)=>{const party=[{email:user.email,display_name:user.displayName,track,checkpoint:completed.length,xp},...friends].filter(f=>f.track===track&&Number(f.checkpoint||0)>=phase.first&&Number(f.checkpoint||0)<phase.first+phase.count);return <div className={`map-stage ${nextId>=phase.first?"reached":""}`} key={phase.name}><div className="map-line"/><div className="map-node"><span>{phase.rank}</span></div><b>{phase.name.replace(" Gate","")}</b><small>{phase.count} missions</small><div className="party-markers">{party.map((m,i)=><div className={`party-avatar ${m.email===user.email?"me":""}`} title={`${m.display_name||m.email} · ${m.xp||0} XP`} key={`${m.email}-${i}`}>{(m.display_name||m.email).split(/\s|@/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}</div>)}</div></div>})}</div></section>
    </section><aside className="right-column"><section className="panel course-rules"><div className="panel-title"><span>HOW PROGRESS WORKS</span><ShieldCheck/></div><ol><li><b>Briefing</b><span>Start from plain language, prerequisites and terminology.</span></li><li><b>Training</b><span>Follow guided steps and observe why each result occurs.</span></li><li><b>Hunter Notes</b><span>Review alternatives, trade-offs and stronger practices.</span></li><li><b>Quest</b><span>Solve an independent real-world build challenge.</span></li><li><b>Rank Trial</b><span>Submit evidence and prove understanding.</span></li></ol></section><section className="panel mastery"><div className="panel-title"><span>JOURNEY READINESS</span><b>{track}</b></div>{[["Understand",progress],["Implement",progress],["Debug",Math.max(0,progress-10)],["Test",Math.max(0,progress-15)],["Operate",Math.max(0,progress-25)]].map(([l,v])=><div className="skill" key={l as string}><div><span>{l}</span><b>{v}%</b></div><Progress value={v as number}/></div>)}</section><section className="panel reward-vault" id="vault"><div className="panel-title"><span>REWARD VAULT</span><Gift/></div><div className="vault-count"><b>{unlockedRewards.length}</b><span>collectibles unlocked</span></div>{unlockedRewards.length===0?<p>Clear a side quest to unlock original stickers, quotes and titles.</p>:<div className="vault-items">{unlockedRewards.slice(-3).map(reward=><div key={reward.name}><span>{reward.kind==="Sticker"?"✦":reward.kind==="Quote"?"❝":"♛"}</span><div><b>{reward.name}</b><small>{reward.kind}</small></div></div>)}</div>}</section><section className="panel boss" id="capstone"><div className="boss-icon"><Trophy/></div><span>FINAL RANK TRIAL</span><h3>{capstoneKey?capstoneOptions[track].find(option=>option.id===capstoneKey)?.title:missions.at(-1)?.title}</h3><p>{capstoneKey?"Chosen domain locked to this journey until you change it inside the capstone mission.":"Choose from e-commerce, library, financial accounts, stock trading or student registration."}</p><div>{nextId>=missions.length-1?<Sparkles/>:<LockKeyhole/>}{nextId>=missions.length-1?"Domain selection available":"Complete prior missions"}</div></section><a className="signout-card" href="/signout-with-chatgpt?return_to=/"><LogOut/> Sign out of LevelCraft</a></aside></div><footer><span>LEVELCRAFT 2.0 // BRIEF → TRAIN → BUILD → BREAK → FIX → PROVE → ASCEND</span><span>Java 17 · Spring · Spring Boot</span></footer></main></div>;
}
